import { useEffect, useState } from 'react'
import { cancelEvaluation, enableEvaluationCorrection, getEvaluation, listEvaluations, listWorkers, listCatalog, scheduleNextEvaluation, type CatalogItem, type EvaluationItem, type WorkerItem } from '../../lib/api'

export function EvaluationsPage({ canAdminister, canSchedule }: { canAdminister: boolean; canSchedule: boolean }) {
  const [items, setItems] = useState<EvaluationItem[]>([]); const [workers, setWorkers] = useState<WorkerItem[]>([]); const [positions, setPositions] = useState<CatalogItem[]>([]); const [selected, setSelected] = useState<EvaluationItem | null>(null); const [filter, setFilter] = useState(''); const [error, setError] = useState('')
  async function load() { try { const [evaluations, workerItems, positionItems] = await Promise.all([listEvaluations(), listWorkers(), listCatalog('puestos')]); setItems(evaluations); setWorkers(workerItems); setPositions(positionItems) } catch (reason) { setError(message(reason)) } }
  useEffect(() => { void load() }, [])
  const visible = filter ? items.filter((item) => item.estado === filter) : items
  function workerName(id: number) { const worker = workers.find((item) => item.id === id); return worker ? `${worker.codigo} · ${worker.nombres} ${worker.apellidos}` : `Trabajador #${id}` }
  function positionName(id: number) { return positions.find((item) => item.id === id)?.nombre ?? `Puesto #${id}` }
  async function open(id: number) { try { setSelected(await getEvaluation(id)) } catch (reason) { setError(message(reason)) } }
  async function annul(id: number) { const reason = window.prompt('Motivo obligatorio para habilitar una nueva evaluación'); if (!reason?.trim()) return; try { await cancelEvaluation(id, reason.trim()); setSelected(null); await load() } catch (reason) { setError(message(reason)) } }
  async function enableCorrection(id: number) { const reason = window.prompt('Motivo obligatorio de la corrección (36 horas)'); if (!reason?.trim()) return; try { setSelected(await enableEvaluationCorrection(id, reason.trim())) } catch (reason) { setError(message(reason)) } }
  async function schedule(id: number) { const date = window.prompt('Nueva fecha dentro de los próximos 15 días (AAAA-MM-DD)'); if (!date) return; try { setSelected(await scheduleNextEvaluation(id, date)) } catch (reason) { setError(message(reason)) } }
  if (selected) return <EvaluationDetail item={selected} workerName={workerName(selected.trabajador_id)} positionName={positionName(selected.puesto_id)} onBack={() => setSelected(null)} onCancel={() => void annul(selected.id)} onCorrection={() => void enableCorrection(selected.id)} onSchedule={() => void schedule(selected.id)} canAdminister={canAdminister} canSchedule={canSchedule} />
  return <div className="process-page evaluation-list-page"><div className="process-heading"><div><p className="eyebrow">Historial operativo</p><h2>Evaluaciones</h2></div><span>{visible.length} registros</span></div><div className="worker-filters"><select value={filter} onChange={(event) => setFilter(event.target.value)}><option value="">Todos los estados</option><option value="completada">Completadas</option><option value="borrador">Borradores</option><option value="anulada">Anuladas</option></select></div>{error && <p className="form-error">{error}</p>}<div className="data-table">{visible.map((item) => <button className="evaluation-row" key={item.id} onClick={() => void open(item.id)}><strong>{workerName(item.trabajador_id)}</strong><span>{positionName(item.puesto_id)}</span><span>{new Date(`${item.fecha}T00:00:00`).toLocaleDateString('es-CL')}</span><span className={`status-pill status-${item.estado}`}>{label(item.estado)}</span><span>{result(item)}</span><span className="view-action">Ver detalle →</span></button>)}{!visible.length && <div className="table-empty">No hay evaluaciones para mostrar.</div>}</div></div>
}

function EvaluationDetail({ item, workerName, positionName, onBack, onCancel, onCorrection, onSchedule, canAdminister, canSchedule }: { item: EvaluationItem; workerName: string; positionName: string; onBack: () => void; onCancel: () => void; onCorrection: () => void; onSchedule: () => void; canAdminister: boolean; canSchedule: boolean }) { return <div className="evaluation-detail"><button className="back-link" onClick={onBack}>← Volver a evaluaciones</button><div className="process-heading"><div><p className="eyebrow">Detalle de evaluación</p><h2>{workerName}</h2><p>{positionName}</p></div><span className={`status-pill status-${item.estado}`}>{label(item.estado)}</span></div><section className="worker-summary detail-summary"><p><strong>Fecha:</strong> {new Date(`${item.fecha}T00:00:00`).toLocaleDateString('es-CL')}</p><p><strong>Resultado:</strong> {result(item)}</p><p><strong>Próxima fecha:</strong> {item.proxima_fecha ? new Date(`${item.proxima_fecha}T00:00:00`).toLocaleDateString('es-CL') : 'No programada'}</p><p><strong>Ejecutor:</strong> {item.evaluador_id ? `Evaluador #${item.evaluador_id}` : item.supervisor_id ? `Supervisor #${item.supervisor_id}` : 'No informado'}</p><p><strong>Observaciones:</strong> {item.observaciones || 'Sin observaciones'}</p>{item.motivo_anulacion && <p><strong>Motivo de anulación:</strong> {item.motivo_anulacion}</p>}</section><div className="data-table evaluation-details">{item.detalles.map((detail) => <div className="table-row" key={detail.id}><strong>Competencia #{detail.requisito_id}</strong><span>Nivel obtenido: {detail.nivel_obtenido}</span><span>Mínimo: {detail.nivel_minimo}</span><span className={detail.aprobado ? 'check-approved' : 'check-pending'}>{detail.aprobado ? 'Aprobado' : 'No aprobado'}</span></div>)}</div>{canSchedule && item.estado === 'completada' && <button className="secondary-action" onClick={onSchedule}>Asignar fecha próxima</button>}{canAdminister && item.estado === 'completada' && <button className="secondary-action" onClick={onCorrection}>Habilitar corrección por 36 horas</button>}{canAdminister && item.estado !== 'anulada' && <button className="secondary-action" onClick={onCancel}>Anular y habilitar reevaluación</button>}</div> }

function result(item: EvaluationItem) { if (!item.detalles.length) return 'Sin notas'; const approved = item.detalles.filter((detail) => detail.aprobado).length; return `${approved}/${item.detalles.length} aprobadas` }
function label(value: EvaluationItem['estado']) { return value === 'completada' ? 'Completada' : value === 'borrador' ? 'Borrador' : 'Anulada' }
function message(reason: unknown) { return reason instanceof Error ? reason.message : 'No se pudieron cargar las evaluaciones' }
