from app.models.capacitacion import PlanCapacitacion, PlanCapacitacionActividad
from app.models.catalogos import (
    Actividad,
    ActividadArea,
    ActividadCriterio,
    ActividadCriterioCompetencia,
    ActividadMaquina,
    Area,
    BorradorImportacionMatriz,
    Cargo,
    Competencia,
    CriterioIndicador,
    ImportacionMatriz,
    Maquina,
    MaquinaProceso,
    MatrizPuestoVersion,
    Proceso,
    Puesto,
    PuestoActividad,
    PuestoActividadCompetencia,
    PuestoActividadCriterio,
    PuestoActividadCriterioRequisito,
    PuestoMaquina,
    Turno,
)
from app.models.evaluaciones import (
    Evaluacion,
    EvaluacionCriterio,
    EvaluacionDetalle,
    EvaluacionVersion,
)
from app.models.personas import (
    AsignacionLaboral,
    Evaluador,
    Supervisor,
    Trabajador,
    TrabajadorPuesto,
    TrabajadorSupervisor,
)
from app.models.secuencias import SecuenciaCodigo
from app.models.seguridad import Permiso, Rol, Usuario

__all__ = [
    "Actividad",
    "ActividadArea",
    "ActividadCriterio",
    "ActividadCriterioCompetencia",
    "ActividadMaquina",
    "PlanCapacitacion",
    "PlanCapacitacionActividad",
    "Area",
    "BorradorImportacionMatriz",
    "AsignacionLaboral",
    "Cargo",
    "Competencia",
    "CriterioIndicador",
    "ImportacionMatriz",
    "Evaluacion",
    "EvaluacionDetalle",
    "EvaluacionCriterio",
    "EvaluacionVersion",
    "Evaluador",
    "Permiso",
    "Rol",
    "SecuenciaCodigo",
    "Maquina",
    "MaquinaProceso",
    "MatrizPuestoVersion",
    "Proceso",
    "Puesto",
    "PuestoActividad",
    "PuestoActividadCriterio",
    "PuestoActividadCriterioRequisito",
    "PuestoActividadCompetencia",
    "PuestoMaquina",
    "Supervisor",
    "Trabajador",
    "TrabajadorPuesto",
    "TrabajadorSupervisor",
    "Turno",
    "Usuario",
]
