"""add authentication and permissions

Revision ID: 77f98a385b65
Revises: f8e701bc30a1
Create Date: 2026-07-22 09:33:44.041340
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "77f98a385b65"
down_revision: str | None = "f8e701bc30a1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permisos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("codigo", sa.String(length=120), nullable=False),
        sa.Column("nombre", sa.String(length=120), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("modulo", sa.String(length=80), nullable=False),
        sa.Column("accion", sa.String(length=80), nullable=False),
        sa.Column("sistema", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("activo", sa.Boolean(), server_default="1", nullable=False),
        sa.Column(
            "creado_en",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permisos")),
        sa.UniqueConstraint("codigo", name="permiso_codigo"),
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=80), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("sistema", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("activo", sa.Boolean(), server_default="1", nullable=False),
        sa.Column(
            "creado_en",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("nombre", name=op.f("uq_roles_nombre")),
    )
    op.create_table(
        "usuarios",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("correo", sa.String(length=255), nullable=False),
        sa.Column("nombre_completo", sa.String(length=200), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("activo", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("ultimo_acceso", sa.DateTime(), nullable=True),
        sa.Column(
            "creado_en",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usuarios")),
        sa.UniqueConstraint("correo", name=op.f("uq_usuarios_correo")),
        sa.UniqueConstraint("username", name=op.f("uq_usuarios_username")),
    )
    op.create_table(
        "rol_permisos",
        sa.Column("rol_id", sa.Integer(), nullable=False),
        sa.Column("permiso_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permiso_id"],
            ["permisos.id"],
            name=op.f("fk_rol_permisos_permiso_id_permisos"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["rol_id"],
            ["roles.id"],
            name=op.f("fk_rol_permisos_rol_id_roles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("rol_id", "permiso_id", name=op.f("pk_rol_permisos")),
    )
    op.create_table(
        "usuario_roles",
        sa.Column("usuario_id", sa.Integer(), nullable=False),
        sa.Column("rol_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["rol_id"],
            ["roles.id"],
            name=op.f("fk_usuario_roles_rol_id_roles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuarios.id"],
            name=op.f("fk_usuario_roles_usuario_id_usuarios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("usuario_id", "rol_id", name=op.f("pk_usuario_roles")),
    )
    with op.batch_alter_table("evaluaciones", schema=None) as batch_op:
        batch_op.add_column(sa.Column("supervisor_id", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column("usuario_ejecutor_id", sa.Integer(), nullable=True)
        )
        batch_op.alter_column("evaluador_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.create_foreign_key(
            batch_op.f("fk_evaluaciones_usuario_ejecutor_id_usuarios"),
            "usuarios",
            ["usuario_ejecutor_id"],
            ["id"],
            ondelete="RESTRICT",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_evaluaciones_supervisor_id_supervisores"),
            "supervisores",
            ["supervisor_id"],
            ["id"],
            ondelete="RESTRICT",
        )
        batch_op.create_check_constraint(
            "ejecutor_autorizado",
            "(supervisor_id IS NOT NULL) != (evaluador_id IS NOT NULL)",
        )

    with op.batch_alter_table("evaluadores", schema=None) as batch_op:
        batch_op.add_column(sa.Column("usuario_id", sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(
            batch_op.f("uq_evaluadores_usuario_id"), ["usuario_id"]
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_evaluadores_usuario_id_usuarios"),
            "usuarios",
            ["usuario_id"],
            ["id"],
            ondelete="SET NULL",
        )

    with op.batch_alter_table("supervisores", schema=None) as batch_op:
        batch_op.add_column(sa.Column("usuario_id", sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(
            batch_op.f("uq_supervisores_usuario_id"), ["usuario_id"]
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_supervisores_usuario_id_usuarios"),
            "usuarios",
            ["usuario_id"],
            ["id"],
            ondelete="SET NULL",
        )

    permisos = sa.table(
        "permisos",
        sa.column("codigo", sa.String()),
        sa.column("nombre", sa.String()),
        sa.column("descripcion", sa.Text()),
        sa.column("modulo", sa.String()),
        sa.column("accion", sa.String()),
        sa.column("sistema", sa.Boolean()),
        sa.column("activo", sa.Boolean()),
    )
    permission_codes = [
        "usuarios.ver",
        "usuarios.crear",
        "usuarios.editar",
        "usuarios.desactivar",
        "roles.ver",
        "roles.gestionar",
        "permisos.gestionar",
        "catalogos.gestionar",
        "trabajadores.ver",
        "trabajadores.gestionar",
        "asignaciones.gestionar",
        "requisitos.gestionar",
        "evaluaciones.crear",
        "evaluaciones.editar",
        "evaluaciones.completar",
        "evaluaciones.anular",
        "evaluaciones.consultar",
        "capacitacion.consultar",
    ]
    op.bulk_insert(
        permisos,
        [
            {
                "codigo": code,
                "nombre": code.replace(".", " ").title(),
                "descripcion": "Permiso predefinido del sistema",
                "modulo": code.split(".")[0],
                "accion": code.split(".")[1],
                "sistema": True,
                "activo": True,
            }
            for code in permission_codes
        ],
    )
    roles = sa.table(
        "roles",
        sa.column("nombre", sa.String()),
        sa.column("descripcion", sa.Text()),
        sa.column("sistema", sa.Boolean()),
        sa.column("activo", sa.Boolean()),
    )
    op.bulk_insert(
        roles,
        [
            {
                "nombre": "Administrador",
                "descripcion": "Acceso total",
                "sistema": True,
                "activo": True,
            },
            {
                "nombre": "Gestor",
                "descripcion": "Gestiona la operación",
                "sistema": True,
                "activo": True,
            },
            {
                "nombre": "Evaluador",
                "descripcion": "Ejecuta evaluaciones",
                "sistema": True,
                "activo": True,
            },
            {
                "nombre": "Supervisor",
                "descripcion": "Ejecuta checklists",
                "sistema": True,
                "activo": True,
            },
            {
                "nombre": "Consulta",
                "descripcion": "Acceso de lectura",
                "sistema": True,
                "activo": True,
            },
        ],
    )
    connection = op.get_bind()
    role_permissions = sa.table(
        "rol_permisos",
        sa.column("rol_id", sa.Integer()),
        sa.column("permiso_id", sa.Integer()),
    )
    admin_id = connection.execute(
        sa.text("SELECT id FROM roles WHERE nombre = 'Administrador'")
    ).scalar_one()
    all_permission_ids = (
        connection.execute(sa.text("SELECT id FROM permisos")).scalars().all()
    )
    connection.execute(
        role_permissions.insert(),
        [
            {"rol_id": admin_id, "permiso_id": permission_id}
            for permission_id in all_permission_ids
        ],
    )
    for role_name, codes in {
        "Gestor": [
            "catalogos.gestionar",
            "trabajadores.ver",
            "trabajadores.gestionar",
            "asignaciones.gestionar",
            "requisitos.gestionar",
        ],
        "Evaluador": [
            "evaluaciones.crear",
            "evaluaciones.editar",
            "evaluaciones.completar",
            "evaluaciones.consultar",
        ],
        "Supervisor": [
            "evaluaciones.crear",
            "evaluaciones.editar",
            "evaluaciones.completar",
            "evaluaciones.consultar",
        ],
        "Consulta": [
            "trabajadores.ver",
            "evaluaciones.consultar",
            "capacitacion.consultar",
        ],
    }.items():
        role_id = connection.execute(
            sa.text("SELECT id FROM roles WHERE nombre = :name"), {"name": role_name}
        ).scalar_one()
        quoted_codes = ",".join("'" + code + "'" for code in codes)
        permission_ids = (
            connection.execute(
                sa.text(f"SELECT id FROM permisos WHERE codigo IN ({quoted_codes})")
            )
            .scalars()
            .all()
        )
        connection.execute(
            role_permissions.insert(),
            [
                {"rol_id": role_id, "permiso_id": permission_id}
                for permission_id in permission_ids
            ],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("supervisores", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_supervisores_usuario_id_usuarios"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("uq_supervisores_usuario_id"), type_="unique"
        )
        batch_op.drop_column("usuario_id")

    with op.batch_alter_table("evaluadores", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_evaluadores_usuario_id_usuarios"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("uq_evaluadores_usuario_id"), type_="unique"
        )
        batch_op.drop_column("usuario_id")

    with op.batch_alter_table("evaluaciones", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_evaluaciones_supervisor_id_supervisores"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_evaluaciones_usuario_ejecutor_id_usuarios"),
            type_="foreignkey",
        )
        batch_op.alter_column(
            "evaluador_id", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.drop_column("usuario_ejecutor_id")
        batch_op.drop_column("supervisor_id")

    op.drop_table("usuario_roles")
    op.drop_table("rol_permisos")
    op.drop_table("usuarios")
    op.drop_table("roles")
    op.drop_table("permisos")
    # ### end Alembic commands ###
