"""add processes and machine assignments

Revision ID: 8f89f430fefb
Revises: 77f98a385b65
Create Date: 2026-07-22 10:38:03.572805
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "8f89f430fefb"
down_revision: str | None = "77f98a385b65"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "procesos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("codigo", sa.String(length=50), nullable=False),
        sa.Column("nombre", sa.String(length=150), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("area_id", sa.Integer(), nullable=False),
        sa.Column("activo", sa.Boolean(), server_default="1", nullable=False),
        sa.Column(
            "creado_en",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["area_id"],
            ["areas.id"],
            name=op.f("fk_procesos_area_id_areas"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_procesos")),
        sa.UniqueConstraint("codigo", name=op.f("uq_procesos_codigo")),
        sa.UniqueConstraint("nombre", name=op.f("uq_procesos_nombre")),
    )
    op.create_table(
        "maquina_procesos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("maquina_id", sa.Integer(), nullable=False),
        sa.Column("proceso_id", sa.Integer(), nullable=False),
        sa.Column("fecha_inicio", sa.Date(), nullable=False),
        sa.Column("fecha_fin", sa.Date(), nullable=True),
        sa.Column(
            "creado_en",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "fecha_fin IS NULL OR fecha_fin >= fecha_inicio",
            name=op.f("ck_maquina_procesos_fechas_validas"),
        ),
        sa.ForeignKeyConstraint(
            ["maquina_id"],
            ["maquinas.id"],
            name=op.f("fk_maquina_procesos_maquina_id_maquinas"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proceso_id"],
            ["procesos.id"],
            name=op.f("fk_maquina_procesos_proceso_id_procesos"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_maquina_procesos")),
    )
    with op.batch_alter_table("maquina_procesos", schema=None) as batch_op:
        batch_op.create_index(
            "uq_maquina_proceso_activo",
            ["maquina_id"],
            unique=True,
            sqlite_where=sa.text("fecha_fin IS NULL"),
        )

    with op.batch_alter_table("puestos", schema=None) as batch_op:
        batch_op.add_column(sa.Column("proceso_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("maquina_id", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "tipo_puesto",
                sa.String(length=20),
                server_default="manual",
                nullable=False,
            )
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_puestos_maquina_id_maquinas"),
            "maquinas",
            ["maquina_id"],
            ["id"],
            ondelete="RESTRICT",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_puestos_proceso_id_procesos"),
            "procesos",
            ["proceso_id"],
            ["id"],
            ondelete="RESTRICT",
        )
        batch_op.create_check_constraint(
            "tipo_puesto_valido", "tipo_puesto IN ('operador', 'ayudante', 'manual')"
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("puestos", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_puestos_proceso_id_procesos"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_puestos_maquina_id_maquinas"), type_="foreignkey"
        )
        batch_op.drop_column("tipo_puesto")
        batch_op.drop_column("maquina_id")
        batch_op.drop_column("proceso_id")

    with op.batch_alter_table("maquina_procesos", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_maquina_proceso_activo", sqlite_where=sa.text("fecha_fin IS NULL")
        )

    op.drop_table("maquina_procesos")
    op.drop_table("procesos")
    # ### end Alembic commands ###
