"""add automatic entity code sequences

Revision ID: f8710cf39a68
Revises: 8f89f430fefb
Create Date: 2026-07-22 11:02:57.350196
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "f8710cf39a68"
down_revision: str | None = "8f89f430fefb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "secuencias_codigos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entidad", sa.String(length=50), nullable=False),
        sa.Column("prefijo", sa.String(length=10), nullable=False),
        sa.Column("siguiente_numero", sa.Integer(), server_default="1", nullable=False),
        sa.Column("longitud", sa.Integer(), server_default="4", nullable=False),
        sa.Column("activo", sa.Boolean(), server_default="1", nullable=False),
        sa.Column(
            "creado_en",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_secuencias_codigos")),
        sa.UniqueConstraint("entidad", name=op.f("uq_secuencias_codigos_entidad")),
        sa.UniqueConstraint("prefijo", name=op.f("uq_secuencias_codigos_prefijo")),
    )
    connection = op.get_bind()
    sequence_table = sa.table(
        "secuencias_codigos",
        sa.column("entidad", sa.String()),
        sa.column("prefijo", sa.String()),
        sa.column("siguiente_numero", sa.Integer()),
        sa.column("longitud", sa.Integer()),
        sa.column("activo", sa.Boolean()),
    )
    entities = {
        "trabajador": ("TRB", "trabajadores"),
        "supervisor": ("SUP", "supervisores"),
        "evaluador": ("EVA", "evaluadores"),
        "competencia": ("CMP", "competencias"),
        "maquina": ("MAQ", "maquinas"),
        "puesto": ("PST", "puestos"),
        "proceso": ("PRO", "procesos"),
    }
    for entity, (prefix, table_name) in entities.items():
        next_number = connection.execute(
            sa.text(
                "SELECT COALESCE(MAX(CAST(SUBSTR(codigo, "
                f"{len(prefix) + 2}) AS INTEGER)), 0) + 1 "
                f"FROM {table_name} WHERE codigo LIKE '{prefix}-%'"
            )
        ).scalar_one()
        connection.execute(
            sequence_table.insert().values(
                entidad=entity,
                prefijo=prefix,
                siguiente_numero=next_number,
                longitud=4,
                activo=True,
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("secuencias_codigos")
    # ### end Alembic commands ###
