"""initial competency model

Revision ID: f8e701bc30a1
Revises:
Create Date: 2026-07-22 01:59:56.973620
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "f8e701bc30a1"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "actividades",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=150), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("activo", sa.Boolean(), server_default="1", nullable=False),
        sa.Column(
            "creado_en",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_actividades")),
        sa.UniqueConstraint("nombre", name=op.f("uq_actividades_nombre")),
    )
    op.create_table(
        "areas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("activo", sa.Boolean(), server_default="1", nullable=False),
        sa.Column(
            "creado_en",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_areas")),
        sa.UniqueConstraint("nombre", name=op.f("uq_areas_nombre")),
    )
    op.create_table(
        "cargos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("activo", sa.Boolean(), server_default="1", nullable=False),
        sa.Column(
            "creado_en",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cargos")),
        sa.UniqueConstraint("nombre", name=op.f("uq_cargos_nombre")),
    )
    op.create_table(
        "competencias",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("codigo", sa.String(length=50), nullable=False),
        sa.Column("nombre", sa.String(length=150), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("activo", sa.Boolean(), server_default="1", nullable=False),
        sa.Column(
            "creado_en",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competencias")),
        sa.UniqueConstraint("codigo", name=op.f("uq_competencias_codigo")),
        sa.UniqueConstraint("nombre", name=op.f("uq_competencias_nombre")),
    )
    op.create_table(
        "evaluadores",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("codigo", sa.String(length=50), nullable=False),
        sa.Column("documento", sa.String(length=50), nullable=False),
        sa.Column("nombres", sa.String(length=120), nullable=False),
        sa.Column("apellidos", sa.String(length=120), nullable=False),
        sa.Column("correo", sa.String(length=255), nullable=True),
        sa.Column("activo", sa.Boolean(), server_default="1", nullable=False),
        sa.Column(
            "creado_en",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evaluadores")),
        sa.UniqueConstraint("codigo", name=op.f("uq_evaluadores_codigo")),
        sa.UniqueConstraint("correo", name=op.f("uq_evaluadores_correo")),
        sa.UniqueConstraint("documento", name=op.f("uq_evaluadores_documento")),
    )
    op.create_table(
        "maquinas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("codigo", sa.String(length=50), nullable=False),
        sa.Column("nombre", sa.String(length=120), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("activo", sa.Boolean(), server_default="1", nullable=False),
        sa.Column(
            "creado_en",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_maquinas")),
        sa.UniqueConstraint("codigo", name=op.f("uq_maquinas_codigo")),
    )
    op.create_table(
        "supervisores",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("codigo", sa.String(length=50), nullable=False),
        sa.Column("documento", sa.String(length=50), nullable=False),
        sa.Column("nombres", sa.String(length=120), nullable=False),
        sa.Column("apellidos", sa.String(length=120), nullable=False),
        sa.Column("correo", sa.String(length=255), nullable=True),
        sa.Column("activo", sa.Boolean(), server_default="1", nullable=False),
        sa.Column(
            "creado_en",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_supervisores")),
        sa.UniqueConstraint("codigo", name=op.f("uq_supervisores_codigo")),
        sa.UniqueConstraint("correo", name=op.f("uq_supervisores_correo")),
        sa.UniqueConstraint("documento", name=op.f("uq_supervisores_documento")),
    )
    op.create_table(
        "trabajadores",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("codigo", sa.String(length=50), nullable=False),
        sa.Column("documento", sa.String(length=50), nullable=False),
        sa.Column("nombres", sa.String(length=120), nullable=False),
        sa.Column("apellidos", sa.String(length=120), nullable=False),
        sa.Column("activo", sa.Boolean(), server_default="1", nullable=False),
        sa.Column(
            "creado_en",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trabajadores")),
        sa.UniqueConstraint("codigo", name=op.f("uq_trabajadores_codigo")),
        sa.UniqueConstraint("documento", name=op.f("uq_trabajadores_documento")),
    )
    op.create_table(
        "turnos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=50), nullable=False),
        sa.Column("activo", sa.Boolean(), server_default="1", nullable=False),
        sa.Column(
            "creado_en",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_turnos")),
        sa.UniqueConstraint("nombre", name=op.f("uq_turnos_nombre")),
    )
    turnos = sa.table(
        "turnos",
        sa.column("nombre", sa.String()),
        sa.column("activo", sa.Boolean()),
    )
    op.bulk_insert(
        turnos,
        [
            {"nombre": "Turno 1", "activo": True},
            {"nombre": "Turno 2", "activo": True},
            {"nombre": "Turno 3", "activo": True},
        ],
    )
    op.create_table(
        "asignaciones_laborales",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trabajador_id", sa.Integer(), nullable=False),
        sa.Column("cargo_id", sa.Integer(), nullable=False),
        sa.Column("area_id", sa.Integer(), nullable=False),
        sa.Column("turno_id", sa.Integer(), nullable=False),
        sa.Column("fecha_inicio", sa.Date(), nullable=False),
        sa.Column("fecha_fin", sa.Date(), nullable=True),
        sa.Column(
            "creado_en",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "fecha_fin IS NULL OR fecha_fin >= fecha_inicio",
            name=op.f("ck_asignaciones_laborales_fechas_validas"),
        ),
        sa.ForeignKeyConstraint(
            ["area_id"],
            ["areas.id"],
            name=op.f("fk_asignaciones_laborales_area_id_areas"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["cargo_id"],
            ["cargos.id"],
            name=op.f("fk_asignaciones_laborales_cargo_id_cargos"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["trabajador_id"],
            ["trabajadores.id"],
            name=op.f("fk_asignaciones_laborales_trabajador_id_trabajadores"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["turno_id"],
            ["turnos.id"],
            name=op.f("fk_asignaciones_laborales_turno_id_turnos"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_asignaciones_laborales")),
    )
    with op.batch_alter_table("asignaciones_laborales", schema=None) as batch_op:
        batch_op.create_index(
            "uq_asignacion_laboral_activa",
            ["trabajador_id"],
            unique=True,
            sqlite_where=sa.text("fecha_fin IS NULL"),
        )

    op.create_table(
        "puestos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("codigo", sa.String(length=50), nullable=False),
        sa.Column("nombre", sa.String(length=150), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("cargo_id", sa.Integer(), nullable=False),
        sa.Column("area_id", sa.Integer(), nullable=False),
        sa.Column("activo", sa.Boolean(), server_default="1", nullable=False),
        sa.Column(
            "creado_en",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["area_id"],
            ["areas.id"],
            name=op.f("fk_puestos_area_id_areas"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["cargo_id"],
            ["cargos.id"],
            name=op.f("fk_puestos_cargo_id_cargos"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_puestos")),
        sa.UniqueConstraint("codigo", name=op.f("uq_puestos_codigo")),
        sa.UniqueConstraint("nombre", name=op.f("uq_puestos_nombre")),
    )
    op.create_table(
        "trabajador_supervisores",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trabajador_id", sa.Integer(), nullable=False),
        sa.Column("supervisor_id", sa.Integer(), nullable=False),
        sa.Column("fecha_inicio", sa.Date(), nullable=False),
        sa.Column("fecha_fin", sa.Date(), nullable=True),
        sa.Column(
            "creado_en",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "fecha_fin IS NULL OR fecha_fin >= fecha_inicio",
            name=op.f("ck_trabajador_supervisores_fechas_validas"),
        ),
        sa.ForeignKeyConstraint(
            ["supervisor_id"],
            ["supervisores.id"],
            name=op.f("fk_trabajador_supervisores_supervisor_id_supervisores"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["trabajador_id"],
            ["trabajadores.id"],
            name=op.f("fk_trabajador_supervisores_trabajador_id_trabajadores"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trabajador_supervisores")),
    )
    with op.batch_alter_table("trabajador_supervisores", schema=None) as batch_op:
        batch_op.create_index(
            "uq_trabajador_supervisor_activo",
            ["trabajador_id"],
            unique=True,
            sqlite_where=sa.text("fecha_fin IS NULL"),
        )

    op.create_table(
        "evaluaciones",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trabajador_id", sa.Integer(), nullable=False),
        sa.Column("evaluador_id", sa.Integer(), nullable=False),
        sa.Column("puesto_id", sa.Integer(), nullable=False),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column(
            "estado", sa.String(length=20), server_default="borrador", nullable=False
        ),
        sa.Column("observaciones", sa.Text(), nullable=True),
        sa.Column(
            "creado_en",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "estado IN ('borrador', 'completada', 'anulada')",
            name=op.f("ck_evaluaciones_estado_valido"),
        ),
        sa.ForeignKeyConstraint(
            ["evaluador_id"],
            ["evaluadores.id"],
            name=op.f("fk_evaluaciones_evaluador_id_evaluadores"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["puesto_id"],
            ["puestos.id"],
            name=op.f("fk_evaluaciones_puesto_id_puestos"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["trabajador_id"],
            ["trabajadores.id"],
            name=op.f("fk_evaluaciones_trabajador_id_trabajadores"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evaluaciones")),
    )
    op.create_table(
        "puesto_actividades",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("puesto_id", sa.Integer(), nullable=False),
        sa.Column("actividad_id", sa.Integer(), nullable=False),
        sa.Column(
            "creado_en",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actividad_id"],
            ["actividades.id"],
            name=op.f("fk_puesto_actividades_actividad_id_actividades"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["puesto_id"],
            ["puestos.id"],
            name=op.f("fk_puesto_actividades_puesto_id_puestos"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_puesto_actividades")),
        sa.UniqueConstraint("puesto_id", "actividad_id", name="puesto_actividad"),
    )
    op.create_table(
        "puesto_maquinas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("puesto_id", sa.Integer(), nullable=False),
        sa.Column("maquina_id", sa.Integer(), nullable=False),
        sa.Column("fecha_inicio", sa.Date(), nullable=False),
        sa.Column("fecha_fin", sa.Date(), nullable=True),
        sa.Column(
            "creado_en",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "fecha_fin IS NULL OR fecha_fin >= fecha_inicio",
            name=op.f("ck_puesto_maquinas_fechas_validas"),
        ),
        sa.ForeignKeyConstraint(
            ["maquina_id"],
            ["maquinas.id"],
            name=op.f("fk_puesto_maquinas_maquina_id_maquinas"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["puesto_id"],
            ["puestos.id"],
            name=op.f("fk_puesto_maquinas_puesto_id_puestos"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_puesto_maquinas")),
    )
    with op.batch_alter_table("puesto_maquinas", schema=None) as batch_op:
        batch_op.create_index(
            "uq_puesto_maquina_activa",
            ["puesto_id"],
            unique=True,
            sqlite_where=sa.text("fecha_fin IS NULL"),
        )

    op.create_table(
        "trabajador_puestos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trabajador_id", sa.Integer(), nullable=False),
        sa.Column("puesto_id", sa.Integer(), nullable=False),
        sa.Column("fecha_inicio", sa.Date(), nullable=False),
        sa.Column("fecha_fin", sa.Date(), nullable=True),
        sa.Column(
            "creado_en",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "fecha_fin IS NULL OR fecha_fin >= fecha_inicio",
            name=op.f("ck_trabajador_puestos_fechas_validas"),
        ),
        sa.ForeignKeyConstraint(
            ["puesto_id"],
            ["puestos.id"],
            name=op.f("fk_trabajador_puestos_puesto_id_puestos"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["trabajador_id"],
            ["trabajadores.id"],
            name=op.f("fk_trabajador_puestos_trabajador_id_trabajadores"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trabajador_puestos")),
        sa.UniqueConstraint(
            "trabajador_id", "puesto_id", "fecha_inicio", name="trabajador_puesto_fecha"
        ),
    )
    with op.batch_alter_table("trabajador_puestos", schema=None) as batch_op:
        batch_op.create_index(
            "uq_trabajador_puesto_activo",
            ["trabajador_id", "puesto_id"],
            unique=True,
            sqlite_where=sa.text("fecha_fin IS NULL"),
        )

    op.create_table(
        "puesto_actividad_competencias",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("puesto_actividad_id", sa.Integer(), nullable=False),
        sa.Column("competencia_id", sa.Integer(), nullable=False),
        sa.Column("nivel_minimo", sa.Integer(), nullable=False),
        sa.Column(
            "creado_en",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "nivel_minimo BETWEEN 1 AND 5",
            name=op.f("ck_puesto_actividad_competencias_nivel_minimo_1_5"),
        ),
        sa.ForeignKeyConstraint(
            ["competencia_id"],
            ["competencias.id"],
            name=op.f("fk_puesto_actividad_competencias_competencia_id_competencias"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["puesto_actividad_id"],
            ["puesto_actividades.id"],
            name=op.f(
                "fk_puesto_actividad_competencias_puesto_actividad_id_puesto_actividades"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_puesto_actividad_competencias")),
        sa.UniqueConstraint(
            "puesto_actividad_id", "competencia_id", name="puesto_actividad_competencia"
        ),
    )
    op.create_table(
        "evaluacion_detalles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("evaluacion_id", sa.Integer(), nullable=False),
        sa.Column("requisito_id", sa.Integer(), nullable=False),
        sa.Column("nivel_obtenido", sa.Integer(), nullable=False),
        sa.Column("nivel_minimo", sa.Integer(), nullable=False),
        sa.Column("observaciones", sa.Text(), nullable=True),
        sa.Column(
            "creado_en",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "actualizado_en",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "nivel_minimo BETWEEN 1 AND 5",
            name=op.f("ck_evaluacion_detalles_nivel_minimo_1_5"),
        ),
        sa.CheckConstraint(
            "nivel_obtenido BETWEEN 1 AND 5",
            name=op.f("ck_evaluacion_detalles_nivel_obtenido_1_5"),
        ),
        sa.ForeignKeyConstraint(
            ["evaluacion_id"],
            ["evaluaciones.id"],
            name=op.f("fk_evaluacion_detalles_evaluacion_id_evaluaciones"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["requisito_id"],
            ["puesto_actividad_competencias.id"],
            name=op.f(
                "fk_evaluacion_detalles_requisito_id_puesto_actividad_competencias"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evaluacion_detalles")),
        sa.UniqueConstraint(
            "evaluacion_id", "requisito_id", name="evaluacion_requisito"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("evaluacion_detalles")
    op.drop_table("puesto_actividad_competencias")
    with op.batch_alter_table("trabajador_puestos", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_trabajador_puesto_activo", sqlite_where=sa.text("fecha_fin IS NULL")
        )

    op.drop_table("trabajador_puestos")
    with op.batch_alter_table("puesto_maquinas", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_puesto_maquina_activa", sqlite_where=sa.text("fecha_fin IS NULL")
        )

    op.drop_table("puesto_maquinas")
    op.drop_table("puesto_actividades")
    op.drop_table("evaluaciones")
    with op.batch_alter_table("trabajador_supervisores", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_trabajador_supervisor_activo", sqlite_where=sa.text("fecha_fin IS NULL")
        )

    op.drop_table("trabajador_supervisores")
    op.drop_table("puestos")
    with op.batch_alter_table("asignaciones_laborales", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_asignacion_laboral_activa", sqlite_where=sa.text("fecha_fin IS NULL")
        )

    op.drop_table("asignaciones_laborales")
    op.drop_table("turnos")
    op.drop_table("trabajadores")
    op.drop_table("supervisores")
    op.drop_table("maquinas")
    op.drop_table("evaluadores")
    op.drop_table("competencias")
    op.drop_table("cargos")
    op.drop_table("areas")
    op.drop_table("actividades")
    # ### end Alembic commands ###
