import { useState } from 'react'
import { downloadImportTemplate, executeImport, validateImport, type ImportIssue } from '../../lib/api'

export function ImportPage() {
  const [file, setFile] = useState<File | null>(null); const [skipExisting, setSkipExisting] = useState(false); const [errors, setErrors] = useState<ImportIssue[]>([]); const [warnings, setWarnings] = useState<ImportIssue[]>([]); const [summary, setSummary] = useState<Record<string, Record<string, number>>>({}); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false)
  async function download() { try { const blob = await downloadImportTemplate(); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'plantilla_carga_masiva.xlsx'; anchor.click(); URL.revokeObjectURL(url) } catch (reason) { setErrors([{ hoja: 'descarga', fila: 0, error: message(reason) }]) } }
  async function validate() { if (!file) { setErrors([{ hoja: 'archivo', fila: 0, error: 'Seleccione un archivo Excel' }]); return }; setBusy(true); setNotice(''); try { const result = await validateImport(file); setErrors(result.errores); setWarnings(result.advertencias); setSummary(result.resumen) } catch (reason) { setErrors([{ hoja: 'archivo', fila: 0, error: message(reason) }]) } finally { setBusy(false) } }
  async function execute() { if (!file || errors.length) return; setBusy(true); try { const result = await executeImport(file, skipExisting); setSummary(result.resumen); setNotice('Importación ejecutada correctamente'); setErrors([]) } catch (reason) { setErrors([{ hoja: 'archivo', fila: 0, error: message(reason) }]) } finally { setBusy(false) } }
  return <div className="import-page"><div className="panel-heading"><div><p className="eyebrow">Configuración</p><h2>Carga masiva</h2></div><button className="secondary-action" onClick={() => void download()}>Descargar plantilla</button></div><p className="helper-text">Cargue catálogos, personas y relaciones desde Excel. Los códigos se generan automáticamente y las celdas vacías no sobrescriben información.</p><section className="import-card"><label className="file-picker">Archivo Excel (.xlsx)<input type="file" accept=".xlsx" onChange={(event) => { setFile(event.target.files?.[0] ?? null); setErrors([]); setSummary({}); setNotice('') }} /></label><label className="import-option"><input type="radio" checked={!skipExisting} onChange={() => setSkipExisting(false)} /> Actualizar campos informados</label><label className="import-option"><input type="radio" checked={skipExisting} onChange={() => setSkipExisting(true)} /> Omitir registros existentes</label><div className="form-actions"><button className="secondary-action" disabled={busy || !file} onClick={() => void validate()}>Validar archivo</button><button className="primary-action" disabled={busy || !file || errors.length > 0} onClick={() => void execute()}>Confirmar importación <span>→</span></button></div></section>{notice && <p className="success-message">{notice}</p>}{errors.length > 0 && <IssueList title="Errores" issues={errors} error />}{warnings.length > 0 && <IssueList title="Advertencias" issues={warnings} />}{Object.keys(summary).length > 0 && <section className="import-summary"><h3>Vista previa</h3>{Object.entries(summary).map(([sheet, values]) => <div className="import-summary-row" key={sheet}><strong>{sheet}</strong><span>Nuevos: {values.nuevos ?? values.creados ?? 0}</span><span>Actualizar: {values.actualizar ?? values.actualizados ?? 0}</span><span>Omitir: {values.omitir ?? values.omitidos ?? 0}</span></div>)}</section>}<aside className="import-help"><strong>Reglas de calidad</strong><p>Use nombres y documentos como referencias. No modifique la columna oculta de ejemplos. Las relaciones se procesan después de los catálogos y una carga con errores no se guarda parcialmente.</p></aside></div>
}

function IssueList({ title, issues, error = false }: { title: string; issues: ImportIssue[]; error?: boolean }) { return <section className={error ? 'import-issues error-list' : 'import-issues'}><h3>{title} ({issues.length})</h3>{issues.slice(0, 100).map((issue, index) => <p key={`${issue.hoja}-${issue.fila}-${index}`}><strong>{issue.hoja}:{issue.fila}</strong> {issue.error ?? issue.advertencia}</p>)}{issues.length > 100 && <small>Se muestran los primeros 100 resultados.</small>}</section> }
function message(reason: unknown) { return reason instanceof Error ? reason.message : 'No se pudo completar la operación' }
