import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import type { ReactNode } from 'react'
import { activateRole, activateUser, deactivateRole, deactivateUser, listPermissions, listRoles, listUsers, resetUserPassword, saveRole, saveUser, type PermissionItem, type RoleItem, type UserItem } from '../../lib/api'

export function UsersManagementPage() {
  const [items, setItems] = useState<UserItem[]>([]); const [roles, setRoles] = useState<RoleItem[]>([]); const [editing, setEditing] = useState<UserItem | null>(null); const [form, setForm] = useState({ username: '', correo: '', nombre_completo: '', password: '', rol_ids: [] as number[] }); const [error, setError] = useState(''); const [notice, setNotice] = useState('')
  async function load() { try { const [userItems, roleItems] = await Promise.all([listUsers(), listRoles()]); setItems(userItems); setRoles(roleItems) } catch (reason) { setError(message(reason)) } }
  useEffect(() => { void load() }, [])
  function reset() { setEditing(null); setForm({ username: '', correo: '', nombre_completo: '', password: '', rol_ids: [] }) }
  function edit(user: UserItem) { setEditing(user); setForm({ username: user.username, correo: user.correo, nombre_completo: user.nombre_completo, password: '', rol_ids: user.roles.map((role) => role.id) }) }
  function toggleRole(id: number) { setForm((current) => ({ ...current, rol_ids: current.rol_ids.includes(id) ? current.rol_ids.filter((value) => value !== id) : [...current.rol_ids, id] })) }
  async function submit(event: FormEvent) { event.preventDefault(); try { const data = { username: form.username, correo: form.correo, nombre_completo: form.nombre_completo, ...(editing ? {} : { password: form.password }), rol_ids: form.rol_ids }; await saveUser(data, editing?.id); setNotice(editing ? 'Usuario actualizado' : 'Usuario creado'); reset(); await load() } catch (reason) { setError(message(reason)) } }
  async function toggle(user: UserItem) { try { if (user.activo) { if (!window.confirm('¿Desactivar este usuario?')) return; await deactivateUser(user.id) } else await activateUser(user.id); await load() } catch (reason) { setError(message(reason)) } }
  async function resetPassword(user: UserItem) { const password = window.prompt('Nueva contraseña (mínimo 8 caracteres)'); if (!password) return; try { await resetUserPassword(user.id, password); setNotice('Contraseña restablecida') } catch (reason) { setError(message(reason)) } }
  return <SecurityPanel title="Usuarios" count={items.length} error={error} notice={notice}><form className="stack-form" onSubmit={submit}><div className="editing-banner">{editing ? `Editando: ${editing.username}` : 'Nuevo usuario'}</div><div className="form-line"><input required placeholder="Usuario" value={form.username} onChange={(event) => setForm({ ...form, username: event.target.value })} /><input required type="email" placeholder="Correo" value={form.correo} onChange={(event) => setForm({ ...form, correo: event.target.value })} /></div><div className="form-line"><input required placeholder="Nombre completo" value={form.nombre_completo} onChange={(event) => setForm({ ...form, nombre_completo: event.target.value })} />{!editing && <input required type="password" minLength={8} placeholder="Contraseña" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} />}</div><div className="permission-grid">{roles.map((role) => <label key={role.id}><input type="checkbox" checked={form.rol_ids.includes(role.id)} onChange={() => toggleRole(role.id)} /> {role.nombre}</label>)}</div><div className="form-actions"><button className="primary-action">{editing ? 'Guardar cambios' : 'Crear usuario'} <span>→</span></button>{editing && <button type="button" className="secondary-action" onClick={reset}>Cancelar</button>}</div></form><div className="data-table security-table">{items.map((user) => <div className="table-row" key={user.id}><strong>{user.nombre_completo}</strong><span>{user.username} · {user.correo}</span><span className="status-pill">{user.activo ? user.roles.map((role) => role.nombre).join(', ') || 'Sin rol' : 'Inactivo'}</span><span className="row-actions"><button onClick={() => edit(user)}>Editar</button><button onClick={() => void resetPassword(user)}>Contraseña</button><button onClick={() => void toggle(user)}>{user.activo ? 'Desactivar' : 'Activar'}</button></span></div>)}</div></SecurityPanel>
}

export function RolesManagementPage() {
  const [items, setItems] = useState<RoleItem[]>([]); const [permissions, setPermissions] = useState<PermissionItem[]>([]); const [editing, setEditing] = useState<RoleItem | null>(null); const [form, setForm] = useState({ nombre: '', descripcion: '', permiso_ids: [] as number[] }); const [error, setError] = useState(''); const [notice, setNotice] = useState('')
  async function load() { try { const [roleItems, permissionItems] = await Promise.all([listRoles(), listPermissions()]); setItems(roleItems); setPermissions(permissionItems) } catch (reason) { setError(message(reason)) } }
  useEffect(() => { void load() }, [])
  function reset() { setEditing(null); setForm({ nombre: '', descripcion: '', permiso_ids: [] }) }
  function edit(role: RoleItem) { setEditing(role); setForm({ nombre: role.nombre, descripcion: role.descripcion ?? '', permiso_ids: role.permisos.map((permission) => permission.id) }) }
  function togglePermission(id: number) { setForm((current) => ({ ...current, permiso_ids: current.permiso_ids.includes(id) ? current.permiso_ids.filter((value) => value !== id) : [...current.permiso_ids, id] })) }
  async function submit(event: FormEvent) { event.preventDefault(); try { await saveRole({ nombre: form.nombre, descripcion: form.descripcion, permiso_ids: form.permiso_ids }, editing?.id); setNotice(editing ? 'Rol actualizado' : 'Rol creado'); reset(); await load() } catch (reason) { setError(message(reason)) } }
  async function toggle(role: RoleItem) { try { if (role.activo) await deactivateRole(role.id); else await activateRole(role.id); await load() } catch (reason) { setError(message(reason)) } }
  return <SecurityPanel title="Roles" count={items.length} error={error} notice={notice}><form className="stack-form" onSubmit={submit}><div className="editing-banner">{editing ? `Editando: ${editing.nombre}` : 'Nuevo rol'}</div><div className="form-line"><input required placeholder="Nombre del rol" value={form.nombre} onChange={(event) => setForm({ ...form, nombre: event.target.value })} /><input placeholder="Descripción" value={form.descripcion} onChange={(event) => setForm({ ...form, descripcion: event.target.value })} /></div><div className="permission-grid">{permissions.map((permission) => <label key={permission.id}><input type="checkbox" checked={form.permiso_ids.includes(permission.id)} onChange={() => togglePermission(permission.id)} /> {permission.codigo}</label>)}</div><div className="form-actions"><button className="primary-action">{editing ? 'Guardar cambios' : 'Crear rol'} <span>→</span></button>{editing && <button type="button" className="secondary-action" onClick={reset}>Cancelar</button>}</div></form><div className="data-table security-table">{items.map((role) => <div className="table-row" key={role.id}><strong>{role.nombre}</strong><span>{role.descripcion || 'Sin descripción'}</span><span className="status-pill">{role.activo ? `${role.permisos.length} permisos` : 'Inactivo'}</span><span className="row-actions"><button onClick={() => edit(role)}>Editar</button><button onClick={() => void toggle(role)}>{role.activo ? 'Desactivar' : 'Activar'}</button></span></div>)}</div></SecurityPanel>
}

function SecurityPanel({ title, count, error, notice, children }: { title: string; count: number; error: string; notice: string; children: ReactNode }) { return <div className="security-management"><div className="panel-heading"><div><p className="eyebrow">Seguridad</p><h2>{title}</h2></div><span>{count} registros</span></div>{error && <p className="form-error">{error}</p>}{notice && <p className="success-message">{notice}</p>}{children}</div> }
function message(reason: unknown) { return reason instanceof Error ? reason.message : 'No se pudo completar la operación' }
