import { useEffect, useState } from 'react'
import type { FormEvent, ReactNode } from 'react'
import { activateCatalog, assignMachineProcess, deactivateCatalog, listCatalog, saveCatalog, type CatalogItem } from '../../lib/api'

export function ProcessManagementPage() {
  const [items, setItems] = useState<CatalogItem[]>([]); const [areas, setAreas] = useState<CatalogItem[]>([]); const [editing, setEditing] = useState<CatalogItem | null>(null); const [form, setForm] = useState({ nombre: '', descripcion: '', area_id: '' }); const [error, setError] = useState('')
  async function load() { try { setItems(await listCatalog('procesos')); setAreas(await listCatalog('areas')) } catch (reason) { setError(message(reason)) } }
  useEffect(() => { void load() }, [])
  function edit(item: CatalogItem) { setEditing(item); setForm({ nombre: item.nombre, descripcion: item.descripcion ?? '', area_id: String(item.area_id ?? '') }) }
  function reset() { setEditing(null); setForm({ nombre: '', descripcion: '', area_id: '' }) }
  async function submit(event: FormEvent) { event.preventDefault(); try { await saveCatalog('procesos', { nombre: form.nombre, descripcion: form.descripcion, area_id: Number(form.area_id) }, editing?.id); reset(); await load() } catch (reason) { setError(message(reason)) } }
  async function toggle(item: CatalogItem) { try { if (item.activo) await deactivateCatalog('procesos', item.id); else await activateCatalog('procesos', item.id); await load() } catch (reason) { setError(message(reason)) } }
  return <StructurePanel title="Procesos" count={items.length} error={error}><form className="stack-form" onSubmit={submit}><div className="form-line"><input required placeholder="Nombre del proceso" value={form.nombre} onChange={(event) => setForm({ ...form, nombre: event.target.value })} /><select required value={form.area_id} onChange={(event) => setForm({ ...form, area_id: event.target.value })}><option value="">Área</option>{areas.map((area) => <option key={area.id} value={area.id}>{area.nombre}</option>)}</select></div><input placeholder="Descripción" value={form.descripcion} onChange={(event) => setForm({ ...form, descripcion: event.target.value })} /><div className="form-actions"><button className="primary-action">{editing ? 'Guardar cambios' : 'Agregar proceso'} <span>+</span></button>{editing && <button type="button" className="secondary-action" onClick={reset}>Cancelar</button>}</div></form><StructureRows items={items} onEdit={edit} onToggle={toggle} /></StructurePanel>
}

export function MachineManagementPage() {
  const [items, setItems] = useState<CatalogItem[]>([]); const [processes, setProcesses] = useState<CatalogItem[]>([]); const [editing, setEditing] = useState<CatalogItem | null>(null); const [form, setForm] = useState({ nombre: '', descripcion: '', process_id: '' }); const [error, setError] = useState('')
  async function load() { try { setItems(await listCatalog('maquinas')); setProcesses(await listCatalog('procesos')) } catch (reason) { setError(message(reason)) } }
  useEffect(() => { void load() }, [])
  function edit(item: CatalogItem) { setEditing(item); setForm({ nombre: item.nombre, descripcion: item.descripcion ?? '', process_id: String(item.proceso_id ?? '') }) }
  function reset() { setEditing(null); setForm({ nombre: '', descripcion: '', process_id: '' }) }
  async function submit(event: FormEvent) { event.preventDefault(); try { const machine = await saveCatalog('maquinas', { nombre: form.nombre, descripcion: form.descripcion }, editing?.id); if (form.process_id) await assignMachineProcess(machine.id, Number(form.process_id)); reset(); await load() } catch (reason) { setError(message(reason)) } }
  async function toggle(item: CatalogItem) { try { if (item.activo) await deactivateCatalog('maquinas', item.id); else await activateCatalog('maquinas', item.id); await load() } catch (reason) { setError(message(reason)) } }
  return <StructurePanel title="Máquinas" count={items.length} error={error}><form className="stack-form" onSubmit={submit}><div className="form-line"><input required placeholder="Nombre de máquina" value={form.nombre} onChange={(event) => setForm({ ...form, nombre: event.target.value })} /><select required value={form.process_id} onChange={(event) => setForm({ ...form, process_id: event.target.value })}><option value="">Proceso</option>{processes.map((process) => <option key={process.id} value={process.id}>{process.nombre}</option>)}</select></div><input placeholder="Descripción" value={form.descripcion} onChange={(event) => setForm({ ...form, descripcion: event.target.value })} /><div className="form-actions"><button className="primary-action">{editing ? 'Guardar cambios' : 'Agregar máquina'} <span>+</span></button>{editing && <button type="button" className="secondary-action" onClick={reset}>Cancelar</button>}</div></form><StructureRows items={items} onEdit={edit} onToggle={toggle} /></StructurePanel>
}

export function PositionManagementPage() {
  const [items, setItems] = useState<CatalogItem[]>([]); const [areas, setAreas] = useState<CatalogItem[]>([]); const [processes, setProcesses] = useState<CatalogItem[]>([]); const [cargos, setCargos] = useState<CatalogItem[]>([]); const [machines, setMachines] = useState<CatalogItem[]>([]); const [editing, setEditing] = useState<CatalogItem | null>(null); const [form, setForm] = useState({ nombre: '', descripcion: '', area_id: '', proceso_id: '', cargo_id: '', maquina_id: '', tipo_puesto: 'manual' }); const [error, setError] = useState('')
  async function load() { try { const [positionItems, areaItems, processItems, cargoItems, machineItems] = await Promise.all([listCatalog('puestos'), listCatalog('areas'), listCatalog('procesos'), listCatalog('cargos'), listCatalog('maquinas')]); setItems(positionItems); setAreas(areaItems); setProcesses(processItems); setCargos(cargoItems); setMachines(machineItems) } catch (reason) { setError(message(reason)) } }
  useEffect(() => { void load() }, [])
  function edit(item: CatalogItem) { setEditing(item); setForm({ nombre: item.nombre, descripcion: item.descripcion ?? '', area_id: String(item.area_id ?? ''), proceso_id: String(item.proceso_id ?? ''), cargo_id: String(item.cargo_id ?? ''), maquina_id: String(item.maquina_id ?? ''), tipo_puesto: item.tipo_puesto ?? 'manual' }) }
  function reset() { setEditing(null); setForm({ nombre: '', descripcion: '', area_id: '', proceso_id: '', cargo_id: '', maquina_id: '', tipo_puesto: 'manual' }) }
  async function submit(event: FormEvent) { event.preventDefault(); try { await saveCatalog('puestos', { nombre: form.nombre, descripcion: form.descripcion, area_id: Number(form.area_id), proceso_id: Number(form.proceso_id), cargo_id: Number(form.cargo_id), maquina_id: form.maquina_id ? Number(form.maquina_id) : null, tipo_puesto: form.tipo_puesto }, editing?.id); reset(); await load() } catch (reason) { setError(message(reason)) } }
  async function toggle(item: CatalogItem) { try { if (item.activo) await deactivateCatalog('puestos', item.id); else await activateCatalog('puestos', item.id); await load() } catch (reason) { setError(message(reason)) } }
  return <StructurePanel title="Puestos" count={items.length} error={error}><form className="stack-form" onSubmit={submit}><div className="form-line"><input required placeholder="Nombre del puesto" value={form.nombre} onChange={(event) => setForm({ ...form, nombre: event.target.value })} /><select required value={form.proceso_id} onChange={(event) => setForm({ ...form, proceso_id: event.target.value })}><option value="">Proceso</option>{processes.map((process) => <option key={process.id} value={process.id}>{process.nombre}</option>)}</select></div><div className="form-line"><select required value={form.area_id} onChange={(event) => setForm({ ...form, area_id: event.target.value })}><option value="">Área</option>{areas.map((area) => <option key={area.id} value={area.id}>{area.nombre}</option>)}</select><select required value={form.cargo_id} onChange={(event) => setForm({ ...form, cargo_id: event.target.value })}><option value="">Cargo</option>{cargos.map((cargo) => <option key={cargo.id} value={cargo.id}>{cargo.nombre}</option>)}</select></div><div className="form-line"><select value={form.maquina_id} onChange={(event) => setForm({ ...form, maquina_id: event.target.value })}><option value="">Sin máquina</option>{machines.map((machine) => <option key={machine.id} value={machine.id}>{machine.nombre}</option>)}</select><select value={form.tipo_puesto} onChange={(event) => setForm({ ...form, tipo_puesto: event.target.value })}><option value="manual">Manual</option><option value="operador">Operador</option><option value="ayudante">Ayudante</option></select></div><input placeholder="Descripción" value={form.descripcion} onChange={(event) => setForm({ ...form, descripcion: event.target.value })} /><div className="form-actions"><button className="primary-action">{editing ? 'Guardar cambios' : 'Agregar puesto'} <span>+</span></button>{editing && <button type="button" className="secondary-action" onClick={reset}>Cancelar</button>}</div></form><StructureRows items={items} onEdit={edit} onToggle={toggle} /></StructurePanel>
}

function StructurePanel({ title, count, error, children }: { title: string; count: number; error: string; children: ReactNode }) { return <><PanelHeading title={title} count={count} /><p className="helper-text">Edite los datos, active o desactive registros sin perder el historial.</p>{error && <p className="form-error">{error}</p>}{children}</> }
function StructureRows({ items, onEdit, onToggle }: { items: CatalogItem[]; onEdit: (item: CatalogItem) => void; onToggle: (item: CatalogItem) => void }) { return <div className="data-table structure-table">{items.map((item) => <div className="table-row" key={item.id}><strong>{item.codigo ?? 'AUTO'} · {item.nombre}</strong><span>{item.descripcion || 'Sin descripción'}</span><span className="status-pill">{item.activo ? 'Activo' : 'Inactivo'}</span><span className="row-actions"><button onClick={() => onEdit(item)}>Editar</button><button onClick={() => void onToggle(item)}>{item.activo ? 'Desactivar' : 'Activar'}</button></span></div>)}</div> }
function PanelHeading({ title, count }: { title: string; count: number }) { return <div className="panel-heading"><div><p className="eyebrow">Configuración</p><h2>{title}</h2></div><span>{count} registros</span></div> }
function message(reason: unknown) { return reason instanceof Error ? reason.message : 'No se pudo completar la operación' }
